type: "transformation"
version: "1.0"
pipeline:
  components:
    Get Pipeline Execution Result:
      type: "table-input"
      parameters:
        componentName: "Get Pipeline Execution Result"
        database: "${prv_metaDB}"
        schema: "${prv_metaSchema}"
        targetTable: "${piv_execidtablename}"
        columnNames:
        - "result"
        timeOffset:
    Extract Pipeline Execution Metadata:
      type: "extract-nested-data-sf"
      sources:
      - "Get Pipeline Execution Result"
      parameters:
        componentName: "Extract Pipeline Execution Metadata"
        includeInputColumns: "Yes"
        columns:
        - name: "startedAt"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "result"
          aliasName: "startedAt"
          isArray: "false"
          include: "true"
        - name: "message"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "result"
          aliasName: "message"
          isArray: "false"
          include: "true"
        - name: "status"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "result"
          aliasName: "status"
          isArray: "false"
          include: "true"
        - name: "finishedAt"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "result"
          aliasName: "finishedAt"
          isArray: "false"
          include: "true"
        outerJoin: "No"
        inputAlias: "i"
        arrayPrefix: "f"
        castingMethod: "Fail on invalid data"
        caseColumnAliasNames: "No"
    Update Status in Log table:
      type: "table-update"
      sources:
      - "Set pipelineExecutionId"
      parameters:
        componentName: "Update Status in Log table"
        warehouse: "[Environment Default]"
        database: "${prv_metaDB}"
        schema: "${prv_metaSchema}"
        targetTable: "PIPELINE_EXECUTION_LOG"
        targetAlias: "target"
        sourceAlias: "input"
        joinExpression:
        - - "\"target\".\"pipelineExecutionId\" = \"input\".\"pipelineExecutionId\""
          - "Case"
        whenMatched:
        - - "1=1"
          - "Update"
        updateMapping:
        - - "startedAt"
          - "startedAt"
        - - "status"
          - "status"
        - - "finishedAt"
          - "finshedAt"
        - - "message"
          - "message"
        includeNotMatched: "No"
    Set pipelineExecutionId:
      type: "calculator"
      sources:
      - "Extract Pipeline Execution Metadata"
      parameters:
        componentName: "Set pipelineExecutionId"
        includeInputColumns: "Yes"
        calculations:
        - - "'${piv_pipelineExecutionId}'"
          - "pipelineExecutionId"
  variables:
    prv_metaSchema:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    prv_metaDB:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    piv_execidtablename:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "stg_ffce0f98aebe463d98aafd971d4a71c9_20241029175726920"
    piv_pipelineExecutionId:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "131aa3fe-61ee-4f4c-82aa-9ec80fa54cef"
design:
  components:
    Get Pipeline Execution Result:
      position:
        x: -500
        "y": 20
      tempMetlId: 1
    Extract Pipeline Execution Metadata:
      position:
        x: -230
        "y": 20
      tempMetlId: 4
    Update Status in Log table:
      position:
        x: 310
        "y": 20
      tempMetlId: 5
    Set pipelineExecutionId:
      position:
        x: 40
        "y": 20
      tempMetlId: 6
  notes:
    "1":
      position:
        x: -600
        "y": -160
      size:
        height: 160
        width: 240
      theme: "white"
      content: |-
        #### Get Pipeline Execution Result
        Retrieves the result of a pipeline execution from stage table.
    "2":
      position:
        x: -340
        "y": -220
      size:
        height: 220
        width: 260
      theme: "white"
      content: |-
        #### Extract Pipeline Execution Metadata
        Extracts nested data from the "result" column of the stage table and outputs values for startedAt, message, status & finishedAt as new columns.
    "3":
      position:
        x: -60
        "y": -180
      size:
        height: 180
        width: 240
      theme: "white"
      content: |-
        #### Set pipelineExecutionId
        Calculates a column with the value of the pipelineExecutionId passed via variables.
    "4":
      position:
        x: 200
        "y": -210
      size:
        height: 210
        width: 250
      theme: "white"
      content: |-
        #### Update Status in Log table
        Updates the status, start/end time and message columns in the PIPELINE_EXECUTION_LOG table for the given pipeline execution id by joining on the id.
